### ISSUE TITLE
icp-ce-with-loadbalancers template does not install VA

### ISSUE THREAD

**Issue by drewdouglass1** [ibm-cloud-architecture/terraform-icp-ibmcloud#13]
I used ICP-EE with the icp-ce-with-loadbalancers template.
I updated the variables.tf to create a VA Node which was created.
A review of the config.yaml file shows only 3 items disabled. 
management_services:
  istio: disabled
  storage-minio: disabled
  storage_glusterfs: disabled
I am sure I can install it, but wanted to make you aware.

**Comment by hassenius** [comment]
As per https://www.ibm.com/support/knowledgecenter/SSBS6K_3.1.1/manage_cluster/vuln_advisor.html
vulnerability advisor is only supported on ICP Enterprise Edition.
So it may for that reason be a little misleading keep the VA instance  definition in the terraform template.

**Comment by drewdouglass1** [comment]
So, even though I used the ICP-EE image gz file the steps to install it are not included in the template?

**Comment by hassenius** [comment]
How did you supply the ICP-EE image? Would you be able to share you config and any template modifications?
